project:
  type: website
  output-dir: docs

website:
  title: "Richard's R Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rnazario2026/workshop_project.git
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: solar
    css: styles.css

editor: visual

